name: ROS2 Humble CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        rosdep update
        # rosdep install --from-paths src --ignore-src -r -y

    - name: Build
      run: |
        . /opt/ros/humble/setup.sh
        colcon build --symlink-install

    - name: Test
      run: |
        . /opt/ros/humble/setup.sh
        colcon test
        colcon test-result --all
